### ISSUE TITLE
Verify no SSLException reported on receiving SSLv2 Client Hello

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-tls.java#8]

**Comment by jfallows** [comment]
TLS nukleus now no longer lets any `SSLException` escape.

**Comment by jfallows** [comment]
Java 9 stack shows the following for SSLv2 Client.
```
java.lang.UnsupportedOperationException: Unsupported SSL v2.0 ClientHello
	at java.base/sun.security.ssl.SSLEngineInputRecord.handleUnknownRecord(SSLEngineInputRecord.java:373)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:195)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:975)
	at java.base/sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:902)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:680)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
```
